name: Sync dev with main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history so we can rebase
      - name: Fetch all branches
        run: git fetch --all
      - name: Checkout dev branch
        run: git checkout dev
      - name: Rebase dev on main
        run: git rebase origin/main
      - name: Push changes to dev
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/reubenthomasjohn/TestRepo.git
          git push --force-with-lease origin dev
