name: Sync dev with main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history so we can rebase
      - name: Fetch all branches
        run: git fetch --all
      - name: Checkout dev branch
        run: git checkout dev
      - name: Rebase dev on main
        run: git rebase main
      - name: Push changes to dev
        run: |
          git push --force-with-lease origin dev
